### ISSUE TITLE
WebSocket Connection Error

### ISSUE THREAD

**Issue by stagnoman** [coinigy/WebsocketAPIClient#2]
It seems not working, I always get error 1005 when I log in
Call to SSPI failed ..... Am I wrong somewhere, any suggestion? 
![error](https://user-images.githubusercontent.com/2866789/30701466-9da5a57c-9eea-11e7-9c6f-e99b8ee933b5.png)

**Comment by robborden** [comment]
Thanks for reporting.  We'll investigate and get back to you.

**Comment by ByronAP** [comment]
@lucastagnitta I can not seem to reproduce. Do you have a copy of your code available anywhere?

**Comment by lucastagnitta** [comment]
here it is, pls change api key and api secret
technically speaking, it was working until last Tuesday, then it began to crash.
Your help will be more than welcome
[WebsocketAPIClient-master.zip](https://github.com/coinigy/WebsocketAPIClient/files/1325760/WebsocketAPIClient-master.zip)

**Comment by lucastagnitta** [comment]
here it is, pls change api key and api secret
technically speaking, it was working until last Tuesday, then it began to crash.
run Demo.exe
Your help will be more than welcome

[WebsocketAPIClient-master.zip](https://github.com/coinigy/WebsocketAPIClient/files/1325771/WebsocketAPIClient-master.zip)

**Comment by stagnoman** [comment]
here it is, pls change api key and api secret
technically speaking, it was working until last Tuesday, then it began to crash.
run Demo.exe
Your help will be more than welcome

[WebsocketAPIClient-master.zip]REMOVED LINK

**Comment by ByronAP** [comment]
I got it and removed the link

**Comment by ByronAP** [comment]
@lucastagnitta Does it take a while to crash? I have been running it for a few minutes and it seems fine.

**Comment by ByronAP** [comment]
do you have anything that would try to interfere with a secure connection like a packet capture device, loopback websocket proxy, it is odd that from what you show it is an ssl error. Can you tell me about  your platform (os, ram, .net version) and network connection?

**Comment by stagnoman** [comment]
when I run the program it doesn' t connect to Coinigy. Last week it was running properly. 
... now it tries to connect x times, then freeze, sometime after 10 mins, others more. Anyway, the key poit is that does not establish a connection and it is refused for some reason
 
quick question: does my demo work on your side? 
I tried in 3 different computers, same result. The main, is a server located in Germany
.Net Framework 4.51

ping vs sc-02.coinigy.com as following, it works correctly
![image](https://user-images.githubusercontent.com/2866789/30771911-f1349ab4-a051-11e7-98b0-59951c2c124b.png)

here server info:
![server](https://user-images.githubusercontent.com/2866789/30771947-d492914e-a052-11e7-942b-cb30aefbe4c0.png)

How can I investigate if there is a Packet capture on my network or loopback websocket proxy? 

I wish it helps
Thks

**Comment by robborden** [comment]
Can you please try the Nuget package PureSocketCluster instead?  I'm not
sure where the client is from that you're using.  It doesn't appear to be
our client that we offer, or the official C# SocketCluster client.

Our: https://github.com/coinigy/PureSocketCluster
Official: https://github.com/sacOO7/SocketclusterClientDotNet

Thanks,
Rob

Thanks,

Rob Borden

**Comment by ByronAP** [comment]
OK I was able to finally reproduce the error, Investigating cause.

**Comment by stagnoman** [comment]
great! thks

**Comment by stagnoman** [comment]
I got the problem
for ssl security reason, you must build the project targeting framework .net >= 4.6
then it works

**Comment by ByronAP** [comment]
yeah It is a known issue in the websockets4net. I am rewriting and expanding this library/repo today since it is out of date and not the quality it should be.

**Comment by ByronAP** [comment]
complete rebuild completed
