### ISSUE TITLE
Subscribe to Channels

### ISSUE THREAD

**Issue by Vannazux** [coinigy/WebsocketAPIClient#4]
Hi @ByronAP,

I am trying to subscribe to multiple channels using your websocket implementation. It works but it seems to retrieve information only for the first channel of the subscribed list, which is BINANCE and get stuck in this exchange. I suppose I did something wrong. Shouldn't the method client_OnOrderMessage() retrieve the information for all the subscribed channels?

Would it be anything related to API`s free accounts restriction limits or would that be an error?

below the code:

private static void Client_OnClientReady()
{
channels = _client.GetChannels();
foreach (var channel in channels)
{
if (channel.Contains("ORDER"))
{
OutputConsole.WriteLine(channel, ConsoleColor.Cyan);
_client.SubscribeToChannel(channel);
}
.....
...
..
}}

**Comment by Vannazux** [comment]
Hi,

Unfortunately we have tried modifying the application in many ways, but still have the problem. Any advice?

Thanks

**Comment by ByronAP** [comment]
account limits
